// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DevFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD_42LSck_UznFNwUevLaBKoCrDxi26rY',
    appId: '1:658213032436:web:0e00cee32b3f2c80bea9a1',
    messagingSenderId: '658213032436',
    projectId: 'prize24-dev',
    authDomain: 'prize24-dev.firebaseapp.com',
    storageBucket: 'prize24-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbO975O_549DvdcWOiPq0V9q6-WohGIdU',
    appId: '1:658213032436:android:5c86400e0826589fbea9a1',
    messagingSenderId: '658213032436',
    projectId: 'prize24-dev',
    storageBucket: 'prize24-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ_RoHNbt6aMjXxxBcJHyLwVcw5Lap5zg',
    appId: '1:658213032436:ios:096471509ec5d61bbea9a1',
    messagingSenderId: '658213032436',
    projectId: 'prize24-dev',
    storageBucket: 'prize24-dev.firebasestorage.app',
    iosBundleId: 'com.kintlearn.prize24-app.dev',
  );
}
