import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:prize24_app/core/models/paginated_result.dart';
import 'package:prize24_app/features/campaign/data/repository/campagin_repository.dart';
import 'package:prize24_app/features/campaign/data/services/i_campaign_services.dart';
import 'package:prize24_app/features/campaign/domain/models/campaign_activity_log.dart';
import 'package:prize24_app/features/campaign/domain/models/campaign_model.dart';
import 'package:prize24_app/features/campaign/domain/models/campaign_sharing_request_model.dart';
import 'package:prize24_app/features/campaign/domain/models/gift_redemption_audit_log_model.dart';
import 'package:riverpod_annotation/riverpod_annotation.dart';
part 'i_campain_repository.g.dart';

abstract class ICampaignRepository {
  /// Add Campaign
  /// Adds a new campaign to the system.
  /// The campaign must have a title, description, vendorId, vendorName,
  /// totalParticipants, totalGifts, visibility, and allowedGiftType.
  /// Returns the created CampaignModel.
  /// Throws an error if the campaign cannot be added.
  /// The campaignId is generated by the backend.
  Future<CampaignModel> addCampaign({required CampaignModel campaign});

  // Edit Campaign
  /// Edits an existing campaign.
  /// If a field is null, it will not be updated.
  /// If a field is not null, it will be updated with the new value.
  /// Fields that can be edited:
  /// - title
  /// - description
  /// - totalParticipants
  /// - totalGifts
  /// - visibility
  /// - allowedGiftType
  Future<void> editCampaign({
    required String campaignId,
    required String? title,
    required String? description,
    required int? totalParticipants,
    required int? totalGifts,
  });

  // Delete Campaign
  /// Deletes a campaign by its ID.
  Future<void> deleteCampaign({required String campaignId});

  /// Scan user's QR code to get the gifts
  Future<void> scanCustomerQrCode({
    required String userId,
    required String campaignId,
  });

  /// Share Campaign -------------------

  Future<void> shareCampaignToVendors({
    /// The user ID of the vendor to be added to the campaign.
    required List<String> recipientIds,

    /// The ID of the campaign to which the vendor is being added.
    required String campaignId,
  });

  Future<void> shareCampaignToVendor({
    /// The user ID of the vendor to be added to the campaign.
    required String recipientId,

    /// The ID of the campaign to which the vendor is being added.
    required String campaignId,
  });

  /// Repsond to a shared campaign request
  /// Action can be 'accept' or 'decline'
  Future<void> respondToSharedCampaignRequest({
    required String requestId,
    // todo: use enums for action
    required String action,
  });

  /// List Campaigns Sharing Requests
  /// Used by Vendor to list all incoming sharing requests
  Future<PaginatedResult<CampaignSharingRequestModel>>
  listCampaignSharingRequests({
    required String vendorId,
    Object? cursor,
    int limit = 20,
  });

  /// Get Campaigns of a Vendor also includes shared campaigns
  Future<List<CampaignModel>> listVendorsAllCampaigns({
    /// The ID of the vendor whose campaigns are to be fetched.
    /// This includes campaigns that are shared with the vendor.
    required String userId,
    // Todo: Workaround for shared campaigns
    required String vendorName,
    required String vendorPhone,
  });

  /// Get Single Campaigns by Campaign ID
  Future<CampaignModel> getSingleCampaginById({required String campaignId});

  /// Check campaign public sliug availability
  Future<bool> isCampaignPublicSlugAvailable({required String publicSlug});

  // List IDs of user's to whom the campaign share request is already sent
  Future<List<String>> listUserIdsOfAlreadySendRequest({
    required String campaignId,
  });

  /// Audit log for campaign Gift Redemption
  Future<PaginatedResult<GiftRedemptionAuditLogModel>>
  getCampaignGiftRedemptionAuditLog({
    required String campaignId,
    Object? cursor,
    int limit = 10,
  });

  /// Activity Log for Campaigns
  /// Retrieves a paginated list of activity log entries for a specific campaign.
  /// Pass the [cursor] returned from the previous call to fetch the next page.
  /// Omit [cursor] (or pass `null`) to fetch the first page.
  /// When the returned list is empty, all pages have been loaded.
  /// When [userId] is provided, results are scoped to logs for that customer.
  Future<PaginatedResult<CampaignActivityLogEntry>> getCampaignActivityLogs({
    required String campaignId,
    String? userId,
    Object? cursor,
    int limit = 20,
  });
}

// Riverpod Provider
@Riverpod(keepAlive: true)
ICampaignRepository campaignRepository(Ref ref) {
  final campaignService = ref.watch(couponServiceProvider);
  return CampaginRepository(campaignService: campaignService);
}
